### PR TITLE
TST: catvs

### PR DESCRIPTION
**Pull request by klauer**
Verifies server functionality with catvs. Addresses #322 

catvs has brought to light some interesting results and fixes. This is based on my Python 3-compatible fork of catvs here: https://github.com/klauer/catvs/tree/py3k (Once we resolve this caproto PR, I'll open a PR to catvs.)

Testing with curio only at the moment.

Status:
```
TestChannel-test_channel_bad PASSED
TestChannel-test_channel_create PASSED
TestChannel-test_echo PASSED
TestScalar-test_get PASSED
TestScalar-test_get_bad FAILED
TestScalar-test_get_convert PASSED
TestScalar-test_monitor PASSED
TestScalar-test_put FAILED
TestScalar-test_put_bad PASSED
TestScalar-test_put_callback PASSED
TestScalar-test_put_callback_bad PASSED
TestArray-test_get_all PASSED
TestArray-test_get_one PASSED
TestArray-test_get_some PASSED
TestArray-test_get_zero PASSED
TestArray-test_get_zero_dynamic PASSED
TestArray-test_monitor_one_fixed PASSED
TestArray-test_monitor_three_fixed FAILED
TestArray-test_monitor_zero_dynamic FAILED
TestArray-test_put FAILED
TestSearchTCP-test_tcplookup PASSED
TestSearchTCP-test_tcplookup_err1 PASSED
TestSearchTCP-test_tcplookup_err2 PASSED
TestSearchTCP-test_tcplookup_old PASSED
TestSearchUDP-test_udplookup PASSED
TestSearchUDP-test_udplookup_err1 PASSED
TestSearchUDP-test_udplookup_err2 PASSED
```

Notes on failures:
1. TestScalar-test_get_bad
This test fails, expecting that the server kills the connection (? response should be `None`). caproto returns `ErrorResponse` instead.

2. TestScalar-test_put
This test puts and, without waiting for notification of the put completion, reads the scalar value back. In epics-base, if this test is passing, presumably the order seen is: `WriteRequest (WriteRequest handled) ReadRequest (ReadRequest handled)`. However, in caproto, we spawn a task to handle a write, allowing it to take an arbitrary amount of time. With no delay between put/get, the following happens: `WriteRequest ReadRequest (ReadRequest handled)  (WriteRequest handled)`. Not sure how to address this - could use input here.

3. TestArray-test_monitor_three_fixed
This test has `[42 45]` written to an array PV, the monitor requests 3 elements, and caproto only returns 2. Looks like we need to pad extra values in this instance, unexpectedly.

4. TestArray-test_monitor_zero_dynamic
This indicates that we need some changes in the high-level server to specify maximum number of elements. As-is, the initial `pvproperty(..., value=[0] * max_count)` defines the element count, but this is not correct. There should probably be a `max_count` parameter in our `pvproperty`. While caproto shouldn't have an issue with dynamically resizing arrays, other clients very likely may.

5. TestArray-test_put
This is the same as (2).

Separately: I definitely have messed up non-catvs-related tests. Need to review them.

### CODE REVIEW

**Comment by tacaswell** [comment]
1. seems like better behavior by caproto
2.  as discussed off-line we could split the write up into two parts, one which is run synchronously in-line and it returns a second co-routine which is put into the task.  This would also give us two bites at the apple for handling different failure modes ("I can not talk to the motor controller I own" vs "The motor controller has informed me the motor is on fire").  Exactly how to split things up between those two could be up to the specific Channel.  I think this split also captures the spirit of put completion better. 
3. We should check if padding out the array is actually what the protocol requires 
4. ok
5. see 2

**Comment by danielballan** [comment]
Failure stats:

```
Failure Count / Tests
---------------------
4 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
1 caproto/tests/test_server.py::test_with_caget[array-curio-int-ChannelType.ENUM]
2 caproto/tests/test_catvs.py::test_catvs[curio-TestScalar-test_put_bad]
1 caproto/tests/test_examples.py::test_ioc_examples[trio-caproto.ioc_examples.subgroups-MyPVGroup-class_kwargs10]
1 caproto/tests/test_catvs.py::test_catvs[curio-TestScalar-test_put_callback_bad]
2 caproto/tests/test_catvs.py::test_catvs[curio-TestArray-test_monitor_one_fixed]
2 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
```

**Comment by danielballan** [comment]
CI repair update: locally, I'm down to one test failure, related to the 'state' channel filter which has some known issues (on my to-do list) unrelated to this PR or the catvs tests.

**Comment by danielballan** [comment]
Existence proof: all tests passed locally.

**Comment by danielballan** [comment]
For reference, a survey of how recent commits, which have all been documentation-related and should not affect the pass rate, fared in CI:

```
13:57 $ python travisfailed.py https://travis-ci.org/NSLS-II/caproto/builds/424837054
<snipped>

Failure Count / Tests
---------------------
3 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
3 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
2 caproto/tests/test_catvs.py::test_catvs[curio-TestArray-test_monitor_one_fixed]
1 caproto/tests/test_server.py::test_with_caget[numpy-asyncio-int-ChannelType.GR_LONG]
1 caproto/tests/test_threading_client.py::test_multithreaded_many_write[epics-base-16-iter2]

14:05 $ python travisfailed.py https://travis-ci.org/NSLS-II/caproto/builds/424786986
<snipped>

Failure Count / Tests
---------------------
4 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
3 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
2 caproto/tests/test_catvs.py::test_catvs[curio-TestArray-test_monitor_one_fixed]
1 caproto/tests/test_server.py::test_with_caget[array-curio-int-ChannelType.GR_LONG]

14:06 $ python travisfailed.py https://travis-ci.org/NSLS-II/caproto/builds/424543665
<snipped>

Failure Count / Tests
---------------------
2 caproto/tests/test_catvs.py::test_catvs[curio-TestArray-test_monitor_one_fixed]
2 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
2 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
1 caproto/tests/test_catvs.py::test_catvs[curio-TestScalar-test_put_callback]
1 caproto/tests/test_catvs.py::test_catvs[curio-TestScalar-test_put_callback_bad]
1 caproto/tests/test_server.py::test_with_caget[array-curio-int-ChannelType.CTRL_LONG]
1 caproto/tests/test_server.py::test_with_caget[numpy-asyncio-int-ChannelType.STS_LONG]
1 caproto/tests/test_server.py::test_with_caget[numpy-curio-pi-ChannelType.CTRL_ENUM]
```

**Comment by klauer** [comment]
Should we `xfail` those specific catvs tests, merge, and focus on CI in a separate PR?

**Comment by danielballan** [comment]
> Should we `xfail` those specific catvs tests, merge, and focus on CI in a separate PR?

Works for me.

I'll go with `flaky` instead of `xfail` to start and see if that's good enough. Since these all pass locally this seems like a flakiness issue.

**Comment by danielballan** [comment]
`flaky` didn't do the trick. There were still some `catvs` failures:

```
$ python travisfailed.py https://travis-ci.org/NSLS-II/caproto/builds/424957802
<snipped>

Failure Count / Tests
---------------------
4 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
3 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
2 caproto/tests/test_catvs.py::test_catvs[curio-TestArray-test_monitor_one_fixed]
1 caproto/tests/test_catvs.py::test_catvs[curio-TestScalar-test_put_callback_bad]
1 caproto/tests/test_server.py::test_with_caget[array-curio-pi-ChannelType.CTRL_CHAR]
1 caproto/tests/test_server.py::test_with_caget[numpy-curio-enum-ChannelType.LONG]

```

**Comment by danielballan** [comment]
Last build:

```
Failure Count / Tests
---------------------
3 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
2 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
1 caproto/tests/test_catvs.py::test_catvs[curio-TestScalar-test_put_bad]
1 caproto/tests/test_server.py::test_with_caget[numpy-curio-enum-ChannelType.CHAR]
1 caproto/tests/test_server.py::test_with_caget[numpy-curio-enum-ChannelType.TIME_INT]
1 caproto/tests/test_server.py::test_with_caget[numpy-curio-pi-ChannelType.CTRL_FLOAT]
```

**Comment by danielballan** [comment]
3 builds passed, and there were not failures from the catvs tests added by this PR.

```
Failure Count / Tests
---------------------
4 caproto/tests/test_channel_filters.py::test_dbnd_filter[{"dbnd":
2 caproto/tests/test_examples.py::test_special_ioc_examples[caproto.ioc_examples.areadetector_image-DetectorGroup-class_kwargs1]
1 caproto/tests/test_bench.py::test_waveform_get[INFO-curio-50000]
1 caproto/tests/test_server.py::test_with_caget[numpy-asyncio-enum-ChannelType.TIME_CHAR]
```

As discussed in private channels, I'll declare victory at this point and carry on battling the ongoing CI problems in a separate PR. The pass rate is better on this PR than it is on current `master`.

**Pull request merged**
