### PR TITLE
REF: try using coloredlogs module

### PR DESCRIPTION
**Pull request by klauer**
Just seeing what this looks like, in place of vendoring the logging from tornado.

### CODE REVIEW

**Comment by danielballan** [comment]
Not sure we want to merge this, but big :+1: for at least trying it out so we know what we like.

**Comment by teddyrendahl** [comment]
Curious as to why this was a no go

**Comment by danielballan** [comment]
It's a fair question. From the beginning we've gone a little out of our way to make all of caproto's core features work with zero external dependencies beyond Python itself. We took the trouble to make numpy optional, falling back on Python's built-in `array` module until numpy is present. We have an `asyncio`-based implementation of the server and, of course, a `threading` implementation of the client --- in addition to other implementations that we find more interesting but require external libraries to use.

This lightness is nice to have in contexts like installing caproto on RaspberryPi, and I guess I just find it entertaining/satisfying as an experiment. If we ever find ourselves needing something big that Python doesn't provide, I would be in favor of importing it rather than reinventing it, but so far Python's built-ins have had all the essential pieces. I vendor-ed (and @klauer simplified) Tornado's color log implementation, and since it's not _that_ large or complex, I don't think it's worth breaking our zero-deps streak in order to use coloredlogs. I would feel differently if caproto already had a bunch of deps.

**Comment by danielballan** [comment]
I appreciate that the above position is a little eccentric. :- D

**Comment by teddyrendahl** [comment]
Didn't mean for it to come off as a pointed question 😄 

We have been happy with `coloredlogs` so I was just curious if there was something about the library itself that turned you away. I appreciate the desire for a pure Python standard lib implementation regardless of the alleged eccentricity 👍

**Comment by danielballan** [comment]
Yeah, no worries, didn't take it personally at all -- I just figured this was a good time to record our thinking in general so I can refer back to it later if/when it comes up again with another module.

**Comment by teddyrendahl** [comment]
😄

**Pull request closed without merging**
