### PR TITLE
CI: initial azure test

### PR DESCRIPTION
**Pull request by klauer**
Auto-generated azure-pipelines.yml

Separate (nonfunctional) work going on in klauer/caproto@azure

### CODE REVIEW

**Comment by mrakitin** [comment]
The error is caused by the absence of the `requirements.txt` file, which is used here: https://github.com/NSLS-II/caproto/pull/372/files#diff-fec826feae04e51c0d94076385408bdcR25. Should it be `test-requirements.txt` instead?

**Comment by danielballan** [comment]
I think @mrakitin is right.

**Comment by klauer** [comment]
You're both right but also wrong - as the initial PR message above makes note, this is just an autogenerated azure configuration straight from the GitHub app. 

I'm working on it in a separate branch and will push here when ready to avoid the annoying spam that's normally associated with CI-related PRs.

**Comment by klauer** [comment]
OK, I've given up on this for now. It's only in a somewhat working state, but not worth wasting more of my time. 

Feel free to pick up where I left off.

**Comment by klauer** [comment]
Why are we still mucking around with travis when Azure looks like this?

image

Yes, the tests fail - but they do on travis, too, in much less obvious ways.

**Comment by tacaswell** [comment]
leroy jenkins.

**Pull request merged**
