### PR TITLE
ENH: add qt5 image viewer example (synchronous/threaded)

### PR DESCRIPTION
**Pull request by klauer**
Synchronous/threaded client image viewer with simple statistics on exit.

(to be updated with a better version soon)

### CODE REVIEW

**Comment by danielballan** [comment]
Care to slap a test on this  -- just something basic to protect it from accidental breakage / bit rot -- and put it in?

**Comment by klauer** [comment]
Can add tests as in what pydm does - do we care if there are even more test deps? (qt5, matplotlib, pytest-qt, ...)

**Comment by danielballan** [comment]
Let's say yes for now. Might want to unwind this later and convert it to a documented example if the set of test requirements starts to feel too heavy, but I think on balance it's good to continually demonstrate support for image-based workflows.

**Comment by danielballan** [comment]
With caproto freshly source-installed from this branch:

```
$ python --version
Python 3.6.4 :: Anaconda, Inc.
```

```
$ python caproto/examples/image_viewer.py
Prefix: 13SIM1: Backend: threaded
PVs: {'acquire': '13SIM1:cam1:Acquire', 'image_mode': '13SIM1:cam1:ImageMode', 'array_data': '13SIM1:image1:ArrayData', 'enabled': '13SIM1:image1:EnableCallbacks', 'unique_id': '13SIM1:image1:UniqueId_RBV', 'array_size0': '13SIM1:image1:ArraySize0_RBV', 'array_size1': '13SIM1:image1:ArraySize1_RBV', 'array_size2': '13SIM1:image1:ArraySize2_RBV', 'color_mode': '13SIM1:image1:ColorMode_RBV', 'bayer_pattern': '13SIM1:image1:BayerPattern_RBV'}
width: 0 height: 0 depth: 0 color_mode: 0
Monitor has begun
1527187738.693618 0 0 0 1 [0] >i4
Traceback (most recent call last):
  File "caproto/examples/image_viewer.py", line 345, in display_image
    image_format = self.image_formats[(color_mode, data_type)]
KeyError: ('0', <ChannelType.LONG: 5>)
Abort trap: 6
```

```
$ python caproto/examples/image_viewer_gl.py
Prefix: 13SIM1: Backend: Threaded/GL
PVs: {'acquire': '13SIM1:cam1:Acquire', 'image_mode': '13SIM1:cam1:ImageMode', 'array_data': '13SIM1:image1:ArrayData', 'enabled': '13SIM1:image1:EnableCallbacks', 'unique_id': '13SIM1:image1:UniqueId_RBV', 'array_size0': '13SIM1:image1:ArraySize0_RBV', 'array_size1': '13SIM1:image1:ArraySize1_RBV', 'array_size2': '13SIM1:image1:ArraySize2_RBV', 'color_mode': '13SIM1:image1:ColorMode_RBV', 'bayer_pattern': '13SIM1:image1:BayerPattern_RBV'}
-------------------------------------------------------------
GL version : 4.1 INTEL-10.14.73
GL vendor  : Intel Inc.
GL renderer: Intel HD Graphics 4000 OpenGL Engine
GL glsl    : 4.10
-------------------------------------------------------------
OpenGL initialized
width: 0 height: 0 depth: 0 color_mode: 0
Monitor has begun
Traceback (most recent call last):
  File "caproto/examples/image_viewer_gl.py", line 271, in image_resized
    width, height = get_image_size(width, height, depth, color_mode)
TypeError: 'NoneType' object is not iterable
Abort trap: 6
```

**Comment by klauer** [comment]
@danielballan please stop reporting errors arising from your usage of `spoof-beamline`... ;)

**Comment by klauer** [comment]
I think this should probably be in a repository of its own for when I work out all of the color modes.
Closing for now.

**Pull request closed without merging**
