### PR TITLE
FIX: CHAR should be treated as unsigned char.

### PR DESCRIPTION
**Pull request by hhslepicka**
This PR also exposes the `SubscriptionType` enum through the `pyepics_compat` layer.

### CODE REVIEW

**Comment by klauer** [comment]
Thanks, @hhslepicka! flake8 is failing due to the unused `SubscriptionType` import, though, causing all the builds to error.

**Comment by hhslepicka** [comment]
Thank you, @klauer . I addressed the issue on the last commit. Sorry about the mess!

**Comment by hhslepicka** [comment]
All tests passed but it failed to build the docs...
I tried locally and docs are building fine...

**Comment by danielballan** [comment]
The docs build now. But it looks like `caproto/tests/test_examples.py::test_mocking_records` is repeatably failing.

**Comment by danielballan** [comment]
...but I can't reproduce that failure locally on this branch. :man_shrugging:

**Comment by danielballan** [comment]
The failure is a timeout that is likely related to this captured stderr:

```
Task exception was never retrieved
future: <Task finished coro=<Context._broadcaster_recv_datagram() done, defined at /home/travis/build/NSLS-II/caproto/caproto/server/common.py:396> exception=KeyError(17,)>
Traceback (most recent call last):
  File "/home/travis/build/NSLS-II/caproto/caproto/server/common.py", line 398, in _broadcaster_recv_datagram
    commands = self.broadcaster.recv(bytes_received, address)
  File "/home/travis/build/NSLS-II/caproto/caproto/_broadcaster.py", line 99, in recv
    commands = read_datagram(byteslike, address, self.their_role)
  File "/home/travis/build/NSLS-II/caproto/caproto/_commands.py", line 305, in read_datagram
    _class = get_command_class(role, header)
  File "/home/travis/build/NSLS-II/caproto/caproto/_commands.py", line 291, in get_command_class
    _class = Commands[role][header.command]
KeyError: 17
```

17 is a `RepeaterConfirmResponse`. It must be flowing the wrong way?

**Comment by klauer** [comment]
OK, that unrelated error is handled in my most recent commit. We should merge this and fix the CI configuration in another PR (as that likely caused the malformed UDP packets).

**Comment by hhslepicka** [comment]
Thank you, @klauer for getting this one through the finish line. 👍

**Pull request merged**
