### PR TITLE
FIX: Correctly handshake with pre-v12 servers.

### PR DESCRIPTION
**Pull request by danielballan**

### CODE REVIEW

**Comment by danielballan** [comment]
Per [Section 4.0 of the spec](https://epics.anl.gov/docs/CAproto.html), servers with protocol Version  < 11 don't send a `VersionResponse` at TCP connection time. Empirically, we are finding that servers with protocol version < 12 have this problem. Maybe the docs are off by one?

**Comment by klauer** [comment]
Thanks to some great git tagging/archiving, we can see the jump from 11 to 13 and the addition of `VersionReply` with:
```diff
$ git diff -w R3.14.10 R3.14.12 -- src/rsrv/caservertask.c src/rsrv/server.h

...clip
@@ -938,6 +936,11 @@ struct client *create_tcp_client ( SOCKET sock )
         return NULL;
     }
 
+    /*
+     * add first version message should it be needed
+     */
+    rsrv_version_reply ( client );
+

...clip


-#define CA_MINOR_PROTOCOL_REVISION 11
+#define CA_MINOR_PROTOCOL_REVISION 13
```

Revision 12 seems harder to find... Will poke around a bit more.

**Comment by danielballan** [comment]
There is a still a confusing piece here. Jeremy (the intern who flagged this issue) reports that this PR fixes the handshake, but shows that we still have a deserialization bug. Notice `data=array([], ...)`:

```py
>>> sub = pv.subscribe()
>>> responses = []
>>> def cb(responses):
...     responses.append(response)
... 
>>> token = sub.add_callback(cb)
[D 16:13:18.242 _circuit:142] Serializing EventAddRequest(data_type=<ChannelType.DOUBLE: 6>, data_count=0, sid=2118, subscriptionid=1, low=0.0, high=0.0, to=0.0, mask=13)
>>> [D 16:13:18.243 _circuit:171] Received 24 bytes.
[D 16:13:18.244 _circuit:181] 16 bytes -> EventAddResponse(data=array([], dtype=float64), data_type=<ChannelType.DOUBLE: 6>, data_count=0, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), subscriptionid=1, metadata=None)
```

But observe that if he sets `data_count=1` explicitly, at my suggestion, the callback works as desired:

```py
>>> sub = pv.subscribe(data_count=1)
>>> responses = []
>>> def cb(responses):
...     responses.append(response)
... 
>>> token = sub.add_callback(cb)
[D 13:42:16.380 _circuit:142] Serializing EventAddRequest(data_type=<ChannelType.DOUBLE: 6>, data_count=1, sid=2121, subscriptionid=1, low=0.0, high=0.0, to=0.0, mask=13)
>>> [D 13:42:16.381 _circuit:171] Received 24 bytes.
[D 13:42:16.382 _circuit:181] 24 bytes -> EventAddResponse(data=array([6258039.]), data_type=<ChannelType.DOUBLE: 6>, data_count=1, status=CAStatusCode(name='ECA_NORMAL', code=0, code_with_severity=1, severity=<CASeverity.SUCCESS: 1>, success=1, defunct=False, description='Normal successful completion'), subscriptionid=1, metadata=None)
```

The `native_data_count` is `1`:

```py
>>> pv.channel.native_data_count
1
```

So I would expect this to work:

https://github.com/NSLS-II/caproto/blob/master/caproto/_circuit.py#L459-L462

and I'm now unclear why setting `data_count=1` explicitly makes any difference....

**Comment by danielballan** [comment]
Ah, the client still thinks it is working with `DEFAULT_PROCOL_VERSION` because it has not seen a `VersionResponse` yet. Commit forthcoming....

**Comment by danielballan** [comment]
FYI, Travis is still very flaky (working on it...) but the threading tests pass locally.

**Comment by tacaswell** [comment]
That seems like a real error:-p

```
self = <PV 'f4da4e39::permit', count=1, type=<ChannelType.TIME_ENUM: 17>, access=read/write>
    @ensure_connection
    def force_read_access_rights(self):
        'Force a read of access rights, not relying on last event callback.'
        self._access_rights_changed(self._caproto_pv.channel.access_rights,
>                                   forced=True)
E       TypeError: _access_rights_changed() missing 1 required positional argument: 'access_rights'
caproto/threading/pyepics_compat.py:502: TypeError
```

**Comment by danielballan** [comment]
That seems like a problem with #329, not this.

**Comment by klauer** [comment]
Yeah, oops. Were travis more reliable, we'd probably merge less bad code...

This looks ready to me. Merge at will.

**Pull request merged**
