### PR TITLE
Revisiting the threading selector

### PR DESCRIPTION
**Pull request by danielballan**
Taking up @klauer valiant work from #83.

(I don't want to force-push to that branch because there has been some major rebasing here....)

### CODE REVIEW

**Comment by tacaswell** [comment]
How did this end up at +10k ?

**Comment by klauer** [comment]
`pytest_bench.json` snuck in there somewhere and is 9k lines

**Comment by danielballan** [comment]
I found that stray file in 284bb498f69a37743188a83de3a93ca7842e1474 and rebased.

**Comment by danielballan** [comment]
All three of us had a hand in this, so I'm not sure who should "review" it... merging.

**Comment by klauer** [comment]
👍

**Pull request merged**
