### PR TITLE
WIP: use select() in threaded client

### PR DESCRIPTION
**Pull request by klauer**
Reduces number of threads in threaded client drastically. Can be reduced further in the future.

 - [ ] threadpool to handle message parsing
 - [x] fix up weakref failed attempt
 - [x] make the selector per-context and not per-process

### CODE REVIEW

**Comment by klauer** [comment]
Tests passing again, finally

**Comment by danielballan** [comment]
This should be rebased soon so that said rebase is not horrible.

**Comment by klauer** [comment]
I'm not so thrilled about continuing work on this PR, if I'm being honest. I think it's probably still the right approach (or closer to it at least - the true right approach would be mirroring how EPICS base handles its potentially hundreds of connections)

**Comment by danielballan** [comment]
Completely fair. I could be up for pushing this across the finish line. I'd like to understand `select` better.

**Comment by danielballan** [comment]
Superceded by #124

**Pull request closed without merging**
