### PR TITLE
ENH: Add server shutdown hook.

### PR DESCRIPTION
**Pull request by danielballan**
Adds a shutdown hook symmetric to the startup hook.

Needs a test.

### CODE REVIEW

**Comment by klauer** [comment]
:+1: Everything as-is looks good. Looks like trio/curio still need support for it, though?

Additionally, if we decide on merging #344 we should also allow the somewhat-magical fields to have `shutdown` support as well. I'd vote in favor of merging this one first and then deciding on the others later.

**Comment by danielballan** [comment]
Rebased. There is a basic test in test examples. Here's an interactive test:

```
17:33 $ python -m caproto.ioc_examples.startup_and_shutdown_hooks --async-lib=asyncio
[I 17:33:17.005 server:149] Server starting up...
[I 17:33:17.005 server:161] Listening on 0.0.0.0:56391
[I 17:33:17.007 server:243] Server startup complete.
starting up
^C[I 17:33:19.095 server:250] Server task cancelled. Will shut down.
[I 17:33:19.096 server:265] Server exiting....
shutting down
(bnl) ✔ ~/Repos/bnl/caproto [server-shutdown ↓·2↑·39|⚑ 9] 
17:33 $ python -m caproto.ioc_examples.startup_and_shutdown_hooks --async-lib=curio
[I 17:33:22.516 server:122] Server starting up...
[I 17:33:22.518 server:143] Listening on 0.0.0.0:60513
[I 17:33:22.518 server:157] Server startup complete.
starting up
^C[I 17:33:22.917 server:165] Server task cancelled. Must shut down.
[I 17:33:22.918 server:168] Server exiting....
shutting down
(bnl) ✔ ~/Repos/bnl/caproto [server-shutdown ↓·2↑·39|⚑ 9] 
17:33 $ python -m caproto.ioc_examples.startup_and_shutdown_hooks --async-lib=trio
[I 17:33:26.090 server:147] Server starting up...
[I 17:33:26.093 server:166] Listening on 0.0.0.0:58119
starting up
[I 17:33:26.095 server:183] Server startup complete.
^C[I 17:33:26.508 server:189] Server exiting....
shutting down

```

**Comment by tacaswell** [comment]
The tasks for asyncio run in parallel, the ones from curio and trio run in series.  Was that intentional?

**Comment by danielballan** [comment]
Not intentional. Added commit to run shutdown in parallel and merged. Thanks!

**Pull request merged**
