### PR TITLE
TST: Fix race condition in threading tests.

### PR DESCRIPTION
**Pull request by danielballan**
I think this should fix some intermittent failures we have seen on Travis.

### CODE REVIEW

**Comment by tacaswell** [comment]
It is true, those failures are no longer intermittent.

**Comment by klauer** [comment]
Good find - those have been bugging me for a while!

**Comment by danielballan** [comment]
I should add some tests that trip all these timeout errors....

**Comment by danielballan** [comment]
Hmm. This does not fix the race condition. It does simplify the code and give better TimeoutErrors though, so worth keeping.

**Comment by danielballan** [comment]
@klauer called the critical fix correctly, in 6b06969. The other commit is not related to the fix, but I do think it improves the code.

**Comment by klauer** [comment]
A+ for persistence

**Pull request merged**
