### PR TITLE
CI: also test py37

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by danielballan** [comment]
Recall this was already discussed here: https://github.com/NSLS-II/caproto/pull/220#issuecomment-430860520

@klauer and I spend a lot of time wrestling with this CI and are reluctant to add builds, at least until we 
make more progress on the flaky threading tests (many of which are X-failed but really should not be).

**Comment by danielballan** [comment]
To tiff on Brett Canon, if a PR is a "free puppy", a PR with an extra CI build is a "free pitbull with emotional damage."

**Comment by tacaswell** [comment]
Sure, but  46f26e6df0663bf03b3dca98162b48df89210faf breaks asyncio servers on py37 but not py36.

**Comment by tacaswell** [comment]
The failure seems to be a bug in cpython that was fixed in 3.7.1 (experimentally, having trouble finding any notes on what it could be).

**Comment by tacaswell** [comment]
The issue that started me down this path turns out to have been an issue with how cpython is compiled (addressed by 077da6300cc930612e77f2d5685bd3a282f9d06a )

Closing in favor of #220 which also adds py37 tests.

**Pull request closed without merging**
