### PR TITLE
FIX: Standardize string encoding and expose ENV var.

### PR DESCRIPTION
**Pull request by danielballan**
- The UTF-8 encoding is not an appropriate default for EPICS (and often blows up on real cases).
- Now the encoding is configurable through an ENV var.

### CODE REVIEW

**Comment by tacaswell** [comment]
What makes utf-8 blow up?!

**Comment by danielballan** [comment]
something something `\x88 is an illegal start byte`

**Comment by danielballan** [comment]
If I understand correctly, all valid ascii is valid UTF-8, but some latin-1 is not valid UTF-8: https://stackoverflow.com/a/7048780/1221924

**Comment by klauer** [comment]
Thanks for fixing this up. 👍 The reality is EPICS is effectively not working with any specific string encoding. A "proper" implementation would always just return byte strings, but this is not so user-friendly to deal with. My opinion is that either 'ascii' or 'latin-1' are about the closest things to what EPICS intended.

**Pull request merged**
