### PR TITLE
MNT: hide import from _data to support py3.4

### PR DESCRIPTION
**Pull request by tacaswell**
attn @dchabot

### CODE REVIEW

**Comment by danielballan** [comment]
Cool. So we'll try to keep the parts of the code that don't use concurrency (the core, the threading client) 3.4-compatible.

**Comment by tacaswell** [comment]
As part of the test refactor you briefly mentioned, we probably should segregate the 3.4 compatible tests and run them (I think the PV tests copied from pyepics should all be 3.4 compatible).

**Comment by klauer** [comment]
Why are we caring about 3.4?

**Comment by tacaswell** [comment]
Because @dchabot asked me if it worked with python <3.5 and the threaded client does work with 3.4 with only this change.

**Comment by klauer** [comment]
OK, in that case it's fine with me. Can you check for 3.4 in the exception block just in case someone dumb (like me) makes an actual syntax error in `_data.py`?

**Comment by danielballan** [comment]
I'm :+1: on support 3.4, but I don't like conditional top-level imports. Let's take the opportunity to move the `_data.py` content in `caproto/server/core.py`. These are helper utilities for implementing servers, not part of the protocol.

I also plan to reorganize the test modules (we have test_threading_pv, test_threading, test_thread_pv...) which is a good excuse to separate 3.4-compatible tests.

**Pull request closed without merging**
